package iti.student.finalproject.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val WeatherPrimaryDark = Color(0xFF1B2541)
val WeatherPrimaryMedium = Color(0xFF2E3A59)
val WeatherSecondaryText = Color(0xFF8C98B8)
val WeatherAccentBlue = Color(0xFF3B82F6)
val WeatherAccentBlueLight = Color(0xFF4FC3F7)
val WeatherAccentBlueDark = Color(0xFF2563EB)
val WeatherAccentGreen = Color(0xFF4CAF50)
val WeatherAccentRed = Color(0xFFF44336)
val WeatherSurfaceCard = Color(0xFFFFFFFF)
val WeatherGradientTop = Color(0xFFF8FAFF)
val WeatherGradientBottom = Color(0xFFE0EAFA)
val WeatherActiveCard = Color(0xFF3B6DF0)
val WeatherYellow = Color(0xFFFBBF24)
val WeatherOrange = Color(0xFFFF8C42)
val WeatherDivider = Color(0xFFE8ECF4)
val WeatherTeal = Color(0xFF06B6D4)
val WeatherPurple = Color(0xFF8B5CF6)
val WeatherCardBorder = Color(0xFFEDF0F7)

val LightBackground = Color(0xFFF8FAFF)
val LightSurface = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF1B2541)
val LightOnSurface = Color(0xFF1B2541)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightOnTertiary = Color(0xFFFFFFFF)

val DarkBackground = Color(0xFF0F172A)
val DarkSurface = Color(0xFF1E293B)
val DarkOnBackground = Color(0xFFE2E8F0)
val DarkOnSurface = Color(0xFFE2E8F0)
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkOnSecondary = Color(0xFF041E24)
val DarkOnTertiary = Color(0xFFFFFFFF)
